name: Build

on: [push, pull_request]

jobs:
  assemble:
    name: Build debug APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Prepare NDK dir for caching
      run: |
        sudo mkdir -p /usr/local/lib/android/sdk/ndk
        sudo chmod -R 777 /usr/local/lib/android/sdk/ndk
        sudo chown -R $USER:$USER /usr/local/lib/android/sdk/ndk
    - name: NDK Cache
      id: ndk-cache
      uses: actions/cache@v2
      with:
        path: /usr/local/lib/android/sdk/ndk
        key: ndk-cache-21.0.6113669-v2
    - name: Install NDK
      if: steps.ndk-cache.outputs.cache-hit != 'true'
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
    - name: Assemble APKs
      run: bash ./gradlew assemble --stacktrace
    - name: Create Debug APK artifiact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
  lint:
    name: Lint Debug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run lint
      run: bash ./gradlew lintDebug --stacktrace
    - name: Create report artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: lint-report
        path: app/build/reports/
